server:
    port: 8081


spring:
    security:
        
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8080/realms/MyRealm/protocol/openid-connect/certs
                    issuer-uri: http://localhost:8080/realms/MyRealm


